- hosts: localhost
  become: false
  tasks:
    - name: Build Docker Image
      include_role:
        name: build-image

    - name: Deploy to Kubernetes
      include_role:
        name: deploy-k8s
